/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4tema4ed;

import java.util.Random;
import javax.swing.DefaultListModel;

/**
 *
 * @author Antonio
 */
public class Quiniela extends javax.swing.JFrame {
    
    private DefaultListModel model;
    /**
     * Creates new form NewJFrame
     */
    public Quiniela() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * metodo para agregar el partido a la lista de partidos
     * @param partido que enfrenta a los dos equipos introducidos
     */
    public void agregarPartido(String partido)
    {
        model= new DefaultListModel();
        for (int i = 0; i < ListPartido.getModel().getSize(); i++) 
        {
            model.addElement(ListPartido.getModel().getElementAt(i));      
        }
        
        model.addElement(partido);
        ListPartido.setModel(model);
    }
    
    /**
     * metodo para eliminar un partido
     * @param numero en la posicion de la lista del partido a borrar
     */
    public void borrar(int numero)
    {
        ListPartido.remove(numero);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorte = new javax.swing.JPanel();
        lQuiniela = new javax.swing.JLabel();
        pNSur = new javax.swing.JPanel();
        lPartido = new javax.swing.JLabel();
        lResultado = new javax.swing.JLabel();
        pSur = new javax.swing.JPanel();
        pPartido = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPartido = new javax.swing.JList<>();
        pBotones = new javax.swing.JPanel();
        bNuevo = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bRealizar = new javax.swing.JButton();
        bResetear = new javax.swing.JButton();
        pResultado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListResultado = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pNorte.setLayout(new java.awt.GridLayout(2, 0));

        lQuiniela.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lQuiniela.setForeground(new java.awt.Color(255, 0, 0));
        lQuiniela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lQuiniela.setText("Quiniela");
        pNorte.add(lQuiniela);

        pNSur.setPreferredSize(new java.awt.Dimension(514, 60));

        lPartido.setText("Partido");

        lResultado.setText("Resultado");

        javax.swing.GroupLayout pNSurLayout = new javax.swing.GroupLayout(pNSur);
        pNSur.setLayout(pNSurLayout);
        pNSurLayout.setHorizontalGroup(
            pNSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNSurLayout.createSequentialGroup()
                .addComponent(lPartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addComponent(lResultado))
        );
        pNSurLayout.setVerticalGroup(
            pNSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNSurLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(pNSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPartido)
                    .addComponent(lResultado))
                .addContainerGap())
        );

        pNorte.add(pNSur);

        getContentPane().add(pNorte, java.awt.BorderLayout.PAGE_START);

        pSur.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pSur.setLayout(new java.awt.GridLayout(1, 3));

        pPartido.setLayout(new java.awt.GridLayout());

        jScrollPane1.setViewportView(ListPartido);

        pPartido.add(jScrollPane1);

        pSur.add(pPartido);

        pBotones.setLayout(new java.awt.GridLayout(4, 0));

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        pBotones.add(bNuevo);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        pBotones.add(bEliminar);

        bRealizar.setText("Realizar Quiniela");
        bRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarActionPerformed(evt);
            }
        });
        pBotones.add(bRealizar);

        bResetear.setText("Resetear");
        bResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetearActionPerformed(evt);
            }
        });
        pBotones.add(bResetear);

        pSur.add(pBotones);

        pResultado.setLayout(new java.awt.GridLayout());

        jScrollPane2.setViewportView(ListResultado);

        pResultado.add(jScrollPane2);

        pSur.add(pResultado);

        getContentPane().add(pSur, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        
        Partido p = new Partido(this);
        
        p.setSize(300, 100);
        
        p.setVisible(true);
    }//GEN-LAST:event_bNuevoActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
       
        DefaultListModel model= (DefaultListModel) ListPartido.getModel();
        int numero=ListPartido.getSelectedIndex();
        model.remove(numero);
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetearActionPerformed
      
        DefaultListModel model=new DefaultListModel();
        ListResultado.setModel(model);
    }//GEN-LAST:event_bResetearActionPerformed

    private void bRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarActionPerformed
        Random aleatorio= new Random();
        DefaultListModel model=new DefaultListModel();
        DefaultListModel model1= (DefaultListModel) ListPartido.getModel();
        String resultado="";
        
        for (int i = 0; i < model1.size(); i++) 
        {
          int numero =aleatorio.nextInt(3-1)+1;
            
            if(numero==1)
            {
                resultado = "X";
            }
            
            else if(numero==2)
            {
                resultado = "1";
            }
            
            else if(numero==3)
            {
                resultado = "2";
            }
         String partid=model1.get(i).toString()+"--> "+resultado;
         model.addElement(partid);
            
        }
          ListResultado.setModel(model);
          ListPartido.setModel(new DefaultListModel());
        
    }//GEN-LAST:event_bRealizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiniela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListPartido;
    private javax.swing.JList<String> ListResultado;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bRealizar;
    private javax.swing.JButton bResetear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lPartido;
    private javax.swing.JLabel lQuiniela;
    private javax.swing.JLabel lResultado;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pNSur;
    private javax.swing.JPanel pNorte;
    private javax.swing.JPanel pPartido;
    private javax.swing.JPanel pResultado;
    private javax.swing.JPanel pSur;
    // End of variables declaration//GEN-END:variables
}
